### ISSUE TITLE
Crashes saying it failed to load the mod

### ISSUE THREAD

**Issue by JackDaniels11111** [welles/BannerlordCheats#19] opened 2020-08-16 07:06 UTC
https://ibb.co/rHbc9Q6

**Comment by welles** [comment] 2020-08-17 11:12
Hi there, sadly the error window does not tell me exactly where the problem is. Can you send me the full list of mods you're using, if any? Maybe it's conflicting with another mod.

**Comment by welles** [comment] 2020-08-24 10:48
Fixed in v1.6.1

**Closed by welles** 2020-08-24 10:48 UTC
Labels: bug, investigating
